# Generated by Django 2.0.5 on 2018-05-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bik', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=50)),
                ('createData', models.DateTimeField()),
                ('info', models.CharField(max_length=100)),
            ],
        ),
    ]
