# Generated by Django 2.0.5 on 2018-05-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banks',
            name='createData',
        ),
        migrations.RemoveField(
            model_name='banks',
            name='info',
        ),
        migrations.AddField(
            model_name='banks',
            name='adress',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banks',
            name='cornumber',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
